### ISSUE TITLE
[BUG] custom path not autodetected

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/docker-odoo#2]
@ivantodorovich can you please take a look to this.
With [this modification](https://github.com/ingadhoc/docker-odoo/commit/ddd84c8f3217e32a300fe841d241a27e4673175a) now the custom repositories are not detecte on the entrypoint.

**Comment by ivantodorovich** [comment]
Fixed here https://github.com/ingadhoc/docker-odoo/commit/49c2a1ade33a4863b0e78834d17e348465f977d3 and here https://github.com/ingadhoc/docker-odoo/commit/91ede18a02a5f919ac164223807454f7002bd4eb

**Comment by jjscarafia** [comment]
thanks @ivantodorovich !
